name: Docker Image Build & Publish

# 実行するイベントの指定
on:
  # 指定ブランチで指定ファイルがPUSHされたときに実行する
  push:
    branches:
      - with-docker

    paths:
      - 'docker/**'
      - '.github/workflows/build-release.yml'

# 環境変数の設定
env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: burger-war-kit
  DOCKER_FILE: docker/kit/Dockerfile
  RELEASE_VERSION: 0.0.1

jobs:
  # ビルドしてGitHub Container Registryにpushする
  build-push:
    # needs: build-test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: |
            # ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
